server:
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mindskeeper
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true